import {
  FileSignature,
  HardHat,
  KeyRound,
  Leaf,
  MessageSquare,
  ShieldCheck,
  Timer,
} from "lucide-react";

import {
  BarricadeIcon,
  CertifiedOperatorIcon,
  HarnessIcon,
  HousekeepingIcon,
  IncidentReportIcon,
  InnovationIcon,
  PermitIcon,
  PpeIcon,
  QualityIcon,
  ReliabilityIcon,
  SafetyIcon,
  SustainabilityIcon,
  ToolboxTalkIcon,
} from "@/components/site/safety-icons";
// Generated by `npm run watermark:photos` - see SITE_PHOTOS below.
import projectPhotos from "@/lib/project-photos.json";

/**
 * Company facts sourced from ACRA / Singapore's public business registry
 * (sgpbusiness.com company profile for PROJECT NOAH PTE. LTD.).
 */
export const company = {
  legalName: "PROJECT NOAH PTE. LTD.",
  brandName: "Project Noah",
  uen: "200807961Z",
  entityType: "Exempt Private Company Limited by Shares",
  status: "Live",
  incorporationDate: "2008-04-23",
  incorporationDateLabel: "23 April 2008",
  countryOfIncorporation: "Singapore",
  address: {
    line1: "1 Soon Lee Street",
    line2: "#05-61 Pioneer Centre",
    postalCode: "Singapore 627605",
    full: "1 Soon Lee Street, #05-61 Pioneer Centre, Singapore 627605",
  },
  primaryActivity: "Building Construction (n.e.c.)",
  secondaryActivity: "Job Training & Vocational Rehabilitation Services",
  phone: "+65 9645 8471",
  whatsapp: "6596458471",
  email: "enquiries@projectnoah.com.sg",
  yearsInOperation: new Date().getFullYear() - 2008,
} as const;

export const SOCIAL_LINKS = {
  youtube: "https://www.youtube.com/@ProjectNoahPTE",
  facebook:
    "https://www.facebook.com/profile.php?id=61591652714784&sk=followers",
  instagram: "https://www.instagram.com/noah200807961z/",
  whatsapp: `https://wa.me/${company.whatsapp}`,
};

export const NAV_LINKS = [
  { label: "About Us", href: "/about" },
  { label: "Our Works", href: "/works" },
  { label: "Services", href: "/#services" },
  { label: "Quality & Safety", href: "/quality-safety" },
  { label: "FAQ", href: "/#faq" },
  { label: "Contact", href: "/contact" },
];

export const SERVICE_CATEGORIES = [
  {
    slug: "roofing-shelter",
    label: "Roofing Services",
    icon: "/services/icons/roofing.png",
    tagline: "Cover, drain and shelter systems",
  },
  {
    slug: "steel-fabrication",
    label: "Steel Services",
    icon: "/services/icons/steel.png",
    tagline: "Structural steel and custom fabrication",
  },
  {
    slug: "facade-renovation",
    label: "Glass Services",
    icon: "/services/icons/glass.png",
    tagline: "Facades, cladding and renovation",
  },
] as const;

export const SERVICES = [
  {
    slug: "roofing-systems",
    category: "roofing-shelter",
    image: "/services/roofing-systems.jpg",
    title: "Roofing Systems",
    description:
      "Roofing design, supply and installation built for Singapore's climate.",
  },
  {
    slug: "canopy-shelter",
    category: "roofing-shelter",
    image: "/services/canopy-shelter.jpg",
    title: "Canopy & Shelter Installation",
    description:
      "Walkway canopies, carpark shelters and loading-bay covers.",
  },
  {
    slug: "awning-solutions",
    category: "roofing-shelter",
    image: "/services/awning-solutions.jpg",
    title: "Awning Solutions",
    description:
      "Custom awnings for shopfronts, windows and outdoor areas.",
  },
  {
    slug: "steel-metal-fabrication",
    category: "steel-fabrication",
    image: "/services/steel-metal-fabrication.jpg",
    title: "Steel & Metal Fabrication",
    description:
      "In-house steel and metal fabrication, brackets to full assemblies.",
  },
  {
    slug: "structural-steel-works",
    category: "steel-fabrication",
    image: "/services/structural-steel-works.jpg",
    title: "Structural Steel Works",
    description:
      "Structural steel erection and reinforcement, engineered to code.",
  },
  {
    slug: "glass-aluminium-works",
    category: "facade-renovation",
    image: "/services/glass-aluminium-works.jpg",
    title: "Glass & Aluminium Works",
    description:
      "Glass panelling, aluminium framing and curtain wall works.",
  },
  {
    slug: "acp-cladding",
    category: "facade-renovation",
    image: "/services/acp-cladding.jpg",
    title: "ACP Cladding",
    description:
      "ACP cladding installation for a durable, modern facade finish.",
  },
  {
    slug: "waterproofing-roof-repairs",
    category: "roofing-shelter",
    image: "/services/waterproofing-roof-repairs.jpg",
    title: "Waterproofing & Roof Repairs",
    description:
      "Leak detection, membrane waterproofing and roof repair works.",
  },
  {
    slug: "gutter-drainage-systems",
    category: "roofing-shelter",
    image: "/services/gutter-drainage-systems.jpg",
    title: "Gutter & Drainage Systems",
    description:
      "Gutter, downpipe and drainage installation and repair.",
  },
  {
    slug: "custom-fabrication",
    category: "steel-fabrication",
    image: "/services/custom-fabrication.jpg",
    title: "Custom Fabrication & Installation",
    description:
      "One-off fabrication and installation scoped to your requirement.",
  },
  {
    slug: "renovation-maintenance",
    category: "facade-renovation",
    image: "/services/renovation-maintenance.jpg",
    title: "Renovation & Maintenance Services",
    description:
      "Renovation, repair and maintenance that keeps buildings in top condition.",
  },
];

export const BENEFITS = [
  {
    icon: Timer,
    title: "Save Time",
    description:
      "A single accountable contractor from tender to handover means fewer handoffs, faster approvals and no lost time chasing subcontractors.",
  },
  {
    icon: ShieldCheck,
    title: "Top Quality & Reliability",
    description:
      "Every phase is signed off against BCA and workplace safety standards before the next trade moves in. Quality checked, not assumed.",
  },
  {
    icon: Leaf,
    title: "Sustainable Building",
    description:
      "Materials and methods chosen to reduce embodied carbon and long-term operating costs, in line with Singapore's Green Mark direction.",
  },
  {
    icon: HardHat,
    title: "Risk Reduction",
    description:
      "18+ years operating as a Singapore-registered entity (UEN 200807961Z), with trained crews and documented safety procedures on every site.",
  },
];

export const PROCESS_STEPS = [
  {
    step: "01",
    title: "Consultation",
    description:
      "We meet on site or virtually to understand scope, budget and timeline before a single drawing is made.",
    icon: MessageSquare,
  },
  {
    step: "02",
    title: "Proposal & Contract",
    description:
      "A itemised quotation and construction programme are issued for sign-off, with scope locked before mobilisation.",
    icon: FileSignature,
  },
  {
    step: "03",
    title: "Construction",
    description:
      "Our site team executes against the programme with weekly progress reporting and safety walk-throughs.",
    icon: HardHat,
  },
  {
    step: "04",
    title: "Handover",
    description:
      "Final inspection, as-built documentation and defect rectification close out the contract, on schedule.",
    icon: KeyRound,
  },
];

/**
 * Quality & Safety page content.
 *
 * The five pillars are the brand's standing promise (the same five that
 * run down the printed site boards), each paired with a hand-drawn glyph
 * from components/site/safety-icons rather than a lucide import - lucide
 * has no harness, cone or permit equivalent, so the whole set is drawn in
 * one language.
 */
export const QUALITY_PILLARS = [
  {
    icon: QualityIcon,
    title: "Quality",
    subtitle: "Workmanship",
    description:
      "Every phase is inspected and signed off before the next trade moves in - so defects are caught at the stage that caused them, not at handover.",
  },
  {
    icon: ReliabilityIcon,
    title: "Reliability",
    subtitle: "You Can Count On",
    description:
      "One accountable contractor from tender to handover, working to an agreed programme with weekly progress reporting.",
  },
  {
    icon: InnovationIcon,
    title: "Innovation",
    subtitle: "Built Into Every Detail",
    description:
      "Details are resolved in fabrication drawings and shop work before they reach site, so installation is assembly rather than improvisation.",
  },
  {
    icon: SafetyIcon,
    title: "Safety",
    subtitle: "Our Priority",
    description:
      "Work at height, hot works and lifting all run to permit, with daily toolbox briefings and documented safety walk-throughs.",
  },
  {
    icon: SustainabilityIcon,
    title: "Sustainability",
    subtitle: "For A Better Future",
    description:
      "Materials and methods chosen to cut waste and long-term operating cost, in line with Singapore's Green Mark direction.",
  },
];

/**
 * Site safety rules - the non-negotiables every crew and visiting
 * subcontractor is briefed on before they are allowed to start work.
 */
export const SAFETY_RULES = [
  {
    icon: PpeIcon,
    title: "Full PPE, No Exceptions",
    description:
      "Helmet, safety footwear, hi-vis and task-specific gloves and eye protection are worn from the moment you pass the gate.",
  },
  {
    icon: HarnessIcon,
    title: "Harness Above 2 Metres",
    description:
      "Any work at height runs to a permit, with a full-body harness clipped to a certified anchor and edge protection in place.",
  },
  {
    icon: ToolboxTalkIcon,
    title: "Toolbox Briefing Every Shift",
    description:
      "The day's scope, hazards and control measures are briefed and signed for before the first tool comes out.",
  },
  {
    icon: PermitIcon,
    title: "Permit-To-Work Controls",
    description:
      "Hot works, confined space entry and lifting operations proceed only against a signed permit and an approved method statement.",
  },
  {
    icon: BarricadeIcon,
    title: "Barricade And Signpost",
    description:
      "Every active work zone, drop zone and opening is hard-barricaded and signed before work starts, not after.",
  },
  {
    icon: CertifiedOperatorIcon,
    title: "Certified Operators Only",
    description:
      "Plant, machinery and lifting gear are handled only by currently certified operators and riggers, with equipment inspected before use.",
  },
  {
    icon: HousekeepingIcon,
    title: "Clear Access, Daily",
    description:
      "Access routes, staircases and escape paths are cleared at the end of every shift - housekeeping is part of the task, not a leftover.",
  },
  {
    icon: IncidentReportIcon,
    title: "Report Within The Shift",
    description:
      "Incidents and near-misses are reported the same shift, investigated, and closed out with a corrective action on record.",
  },
];

/**
 * The Singapore regulatory frame the rules above sit inside. Statutes and
 * codes only - no certification numbers are claimed here, so nothing in
 * this list needs a certificate to back it up.
 */
export const SAFETY_STANDARDS = [
  {
    code: "WSH Act",
    title: "Workplace Safety and Health Act",
    description:
      "Duties of an occupier and contractor to keep the workplace safe, discharged through our risk assessments and control measures.",
  },
  {
    code: "WSH (CONSTRUCTION) REGS",
    title: "WSH (Construction) Regulations",
    description:
      "Site-specific requirements for work at height, scaffolding, formwork, lifting and demolition works.",
  },
  {
    code: "RISK ASSESSMENT",
    title: "WSH (Risk Management) Regulations",
    description:
      "Every scope is risk-assessed and the assessment reviewed before mobilisation and whenever the method changes.",
  },
  {
    code: "BCA",
    title: "BCA Standards & Codes of Practice",
    description:
      "Structural, roofing and facade works executed and inspected against the applicable Building and Construction Authority codes.",
  },
];

/**
 * How a job is checked on its way through - the quality gates that sit
 * between the process steps shown on the About page.
 */
export const QUALITY_CHECKPOINTS = [
  {
    step: "01",
    title: "Material Verification",
    description:
      "Steel, membranes, glass and cladding are checked against the specification and mill or supplier documentation on delivery.",
  },
  {
    step: "02",
    title: "Shop Inspection",
    description:
      "Fabricated assemblies are dimension-checked and weld-inspected in our workshop before anything is loaded for site.",
  },
  {
    step: "03",
    title: "Installation Hold Points",
    description:
      "Set-out, fixing and sealing are inspected at agreed hold points - the next trade only starts once the phase is signed off.",
  },
  {
    step: "04",
    title: "Handover Testing",
    description:
      "Water testing, as-built documentation and a joint defects walk close out the contract before keys change hands.",
  },
];

/**
 * Short-form category labels used for the Our Works filters and each work's
 * `category` field below - must match exactly, or a filter will always
 * render "No works in this category yet."
 */
export const WORK_CATEGORIES = ["All", "Roofing", "Steel", "Glass"] as const;

/**
 * Completed works shown in the Our Works mosaic. Photos are real site
 * photography under public/works - the order here is deliberate: the mosaic
 * cycles fixed tile spans (2x2, 1x2, 1x1, 1x1, 2x1, ...), so each entry sits
 * where its aspect ratio crops well. Reordering will letterbox or over-crop
 * tiles unless the new photo matches the span it lands on.
 */
export const WORKS = [
  {
    slug: "metal-roof-resheeting",
    title: "Metal Roof Re-Sheeting",
    category: "Roofing",
    location: "Singapore",
    year: "2024",
    image: "/works/metal-roof-resheeting.jpg",
    description:
      "New metal roof sheets set out and fixed down over an existing roof, protective film still on as the run is laid.",
  },
  {
    slug: "inter-block-canopy-walkway",
    title: "Covered Walkway Canopy",
    category: "Steel",
    location: "Singapore",
    year: "2023",
    image: "/works/inter-block-canopy-walkway.jpg",
    description:
      "Steel-framed walkway canopy fabricated and installed along a connecting path, weatherproofing the route end to end.",
  },
  {
    slug: "frameless-glass-roof",
    title: "Frameless Glass Roof Installation",
    category: "Glass",
    location: "Singapore",
    year: "2024",
    image: "/works/frameless-glass-roof.jpg",
    description:
      "A frameless faceted glass roof installed over a stairwell, engineered for clean sightlines and full weather sealing.",
  },
  {
    slug: "high-rise-balcony-enclosure",
    title: "High-Rise Balcony Enclosure",
    category: "Glass",
    location: "Singapore",
    year: "2023",
    image: "/works/high-rise-balcony-enclosure.jpg",
    description:
      "Glass roof and enclosure works to a high-rise balcony, adding sheltered usable space with the skyline view kept open.",
  },
  {
    slug: "commercial-walkway-canopy",
    title: "Commercial Walkway Canopy",
    category: "Steel",
    location: "Singapore",
    year: "2023",
    image: "/works/commercial-walkway-canopy.jpg",
    description:
      "Long-span steel canopy frame erected over a commercial walkway, shot mid-install before the roof sheets went on.",
  },
  {
    slug: "sloped-metal-awning",
    title: "Sloped Metal Awning",
    category: "Roofing",
    location: "Singapore",
    year: "2022",
    image: "/works/sloped-metal-awning.jpg",
    description:
      "Sloped metal awning installed off an existing wall, sized to throw rain clear of the openings below.",
  },
  {
    slug: "landed-home-facade-cladding",
    title: "Landed Home Facade Cladding",
    category: "Glass",
    location: "Singapore",
    year: "2022",
    image: "/works/acp-cladding-panels.jpg",
    description:
      "ACP and aluminium cladding panels staged on site, film still on, ahead of facade installation at a landed home.",
  },
  {
    slug: "tile-roof-replacement",
    title: "Tile Roof Replacement",
    category: "Roofing",
    location: "Singapore",
    year: "2022",
    image: "/works/tile-roof-replacement.jpg",
    description:
      "Replacement roof tiles laid and aligned course by course over a re-battened pitched roof.",
  },
  {
    slug: "custom-steel-awning",
    title: "Custom Steel Awning",
    category: "Steel",
    location: "Singapore",
    year: "2021",
    image: "/works/custom-steel-awning.jpg",
    description:
      "One-off steel awning frame fabricated to suit the opening and fixed back to the wall, glazed with translucent sheet.",
  },
  {
    slug: "rooftop-steel-pergola",
    title: "Rooftop Steel Pergola",
    category: "Steel",
    location: "Singapore",
    year: "2021",
    image: "/works/rooftop-steel-pergola.jpg",
    description:
      "Steel pergola frame and roof built out over a rooftop terrace, giving cover without closing off the view.",
  },
  {
    slug: "rooftop-pergola-terrace",
    title: "Rooftop Pergola & Garden Terrace",
    category: "Roofing",
    location: "Singapore",
    year: "2020",
    image: "/works/rooftop-pergola-terrace.jpg",
    description:
      "Timber-finished pergola run across a rooftop garden terrace, shading the seating and planter beds below.",
  },
];

export type SitePhoto = {
  id: string;
  categoryId: string;
  src: string;
  caption: string;
  width: number;
  height: number;
};

/**
 * Extra site photos not tied to a specific work card - shown in the
 * "Photos From Our Sites" gallery. Static files under public/site-photos,
 * served directly rather than through the watermarking /api/images/[id]
 * route that the admin-managed gallery (data/images.json) uses.
 * categoryId must match an id in data/categories.json, or the photo only
 * ever shows under the "All" tab.
 *
 * Hand-curated set. The bulk drop under public/project_images is appended
 * from a generated manifest in SITE_PHOTOS below - keep the two separate so a
 * re-run of `npm run watermark:photos` can rewrite the generated half without
 * touching these.
 */
const CURATED_SITE_PHOTOS: SitePhoto[] = [
  {
    id: "rooftop-shelter-install",
    categoryId: "roofing-shelter",
    src: "/site-photos/rooftop-shelter-install.jpg",
    caption: "Aluminium rooftop shelter going up over a terrace",
    width: 520,
    height: 924,
  },
  {
    id: "pergola-garden-terrace",
    categoryId: "roofing-shelter",
    src: "/site-photos/pergola-garden-terrace.jpg",
    caption: "Pergola shading a rooftop garden terrace",
    width: 720,
    height: 1600,
  },
  {
    id: "rooftop-garden-walkway",
    categoryId: "roofing-shelter",
    src: "/site-photos/rooftop-garden-walkway.jpg",
    caption: "Pergola run along a rooftop garden walkway",
    width: 1600,
    height: 720,
  },
  {
    id: "side-yard-walkway-deck",
    categoryId: "roofing-shelter",
    src: "/site-photos/side-yard-walkway-deck.jpg",
    caption: "Covered side-yard walkway over a timber deck",
    width: 720,
    height: 960,
  },
  {
    id: "metal-roof-tiles",
    categoryId: "roofing-shelter",
    src: "/site-photos/metal-roof-tiles.jpg",
    caption: "Metal roof tiles laid to a pitched roof",
    width: 1200,
    height: 1600,
  },
  {
    id: "standing-seam-metal-roof",
    categoryId: "roofing-shelter",
    src: "/site-photos/standing-seam-metal-roof.jpg",
    caption: "Standing-seam metal roof sheeting",
    width: 1600,
    height: 1600,
  },
  {
    id: "glass-skylight-sky",
    categoryId: "facade-renovation",
    src: "/site-photos/glass-skylight-sky.jpg",
    caption: "Glass skylight panels opening to clear sky",
    width: 1200,
    height: 1600,
  },
  {
    id: "steel-glass-canopy",
    categoryId: "facade-renovation",
    src: "/site-photos/steel-glass-canopy.jpg",
    caption: "Steel-framed glass canopy over an entrance",
    width: 1200,
    height: 1600,
  },
  {
    id: "condo-side-canopy",
    categoryId: "facade-renovation",
    src: "/site-photos/condo-side-canopy.jpg",
    caption: "Glass canopy along a condominium side path",
    width: 720,
    height: 540,
  },
  {
    id: "louvre-ceiling-patio",
    categoryId: "facade-renovation",
    src: "/site-photos/louvre-ceiling-patio.jpg",
    caption: "Aluminium louvre ceiling over a covered patio",
    width: 1024,
    height: 768,
  },
  {
    id: "terrace-glass-roof",
    categoryId: "facade-renovation",
    src: "/site-photos/terrace-glass-roof.jpg",
    caption: "Glass roof across a private terrace",
    width: 720,
    height: 1600,
  },
  {
    id: "aluminium-louvre-screen",
    categoryId: "facade-renovation",
    src: "/site-photos/aluminium-louvre-screen.jpg",
    caption: "Aluminium louvre screen fitted to a facade",
    width: 900,
    height: 1600,
  },
  {
    id: "steel-gable-canopy",
    categoryId: "steel-fabrication",
    src: "/site-photos/steel-gable-canopy.jpg",
    caption: "Steel gable canopy frame with translucent roof",
    width: 1068,
    height: 1068,
  },
  {
    id: "glass-roof-underside",
    categoryId: "steel-fabrication",
    src: "/site-photos/glass-roof-underside.jpg",
    caption: "Underside of a steel-framed glass roof",
    width: 721,
    height: 1599,
  },
  {
    id: "patio-glass-roof-fan",
    categoryId: "steel-fabrication",
    src: "/site-photos/patio-glass-roof-fan.jpg",
    caption: "Steel rafters and glass roof over a patio",
    width: 1024,
    height: 683,
  },
  {
    id: "glass-canopy-timber-deck",
    categoryId: "steel-fabrication",
    src: "/site-photos/glass-canopy-timber-deck.jpg",
    caption: "Glass canopy running above a timber deck",
    width: 1600,
    height: 1600,
  },
];

/**
 * Round-robins photos across their caption groups, largest group first, so the
 * gallery's first page shows a spread of trades instead of sixteen consecutive
 * shots of the same one. Plain concatenation would bury all 112 project photos
 * behind "Load more", since the curated set alone fills the first page.
 *
 * Deterministic on purpose: a random shuffle would order the server and client
 * renders differently and break hydration.
 */
function interleaveByCaption(photos: SitePhoto[]): SitePhoto[] {
  const groups = new Map<string, SitePhoto[]>();
  for (const photo of photos) {
    const group = groups.get(photo.caption);
    if (group) group.push(photo);
    else groups.set(photo.caption, [photo]);
  }

  const queues = [...groups.values()].sort((a, b) => b.length - a.length);
  const ordered: SitePhoto[] = [];
  for (let round = 0; ordered.length < photos.length; round += 1) {
    for (const queue of queues) {
      if (round < queue.length) ordered.push(queue[round]);
    }
  }
  return ordered;
}

/**
 * The curated photos above plus every watermarked photo under
 * public/project_images. The project half is generated - regenerate it with
 * `npm run watermark:photos`, never by hand; the script derives each photo's
 * category and caption from its filename prefix and reads the real pixel
 * dimensions off the watermarked file.
 */
export const SITE_PHOTOS: SitePhoto[] = interleaveByCaption([
  ...CURATED_SITE_PHOTOS,
  ...(projectPhotos as SitePhoto[]),
]);

export const FAQS = [
  {
    question: "Is Project Noah Pte Ltd a registered company in Singapore?",
    answer:
      "Yes. Project Noah Pte Ltd (UEN 200807961Z) is an Exempt Private Company Limited by Shares, incorporated in Singapore on 23 April 2008 and registered with ACRA.",
  },
  {
    question: "What is your registered business activity?",
    answer:
      "Our principal activity on record is Building Construction (n.e.c.), with Job Training & Vocational Rehabilitation Services registered as a secondary activity.",
  },
  {
    question: "Do you handle both new builds and renovation works?",
    answer:
      "Yes, we take on ground-up construction as well as addition & alteration (A&A), retrofitting and fit-out works for existing buildings.",
  },
  {
    question: "What trades do you specialise in?",
    answer:
      "Roofing, canopy & shelter installation, awnings, steel & metal fabrication, structural steel works, glass & aluminium works, ACP cladding, waterproofing, and gutter & drainage systems, plus custom fabrication and ongoing renovation & maintenance.",
  },
  {
    question: "How is a project typically scoped and priced?",
    answer:
      "After an initial site consultation we issue an itemised quotation and construction programme, so scope and cost are agreed before mobilisation begins.",
  },
  {
    question: "Where is Project Noah based?",
    answer:
      "Our registered office is at 1 Soon Lee Street, #05-61 Pioneer Centre, Singapore 627605, and we deliver projects island-wide.",
  },
];
